#!/usr/bin/env python3
"""Format validate.py JSON output as a markdown PR comment.

Reads the JSON contract validate.py exposes via `--format json`:

    {
      "result": "PASS" | "FAIL",
      "total": <int>,
      "passed": <int>,
      "failed": <int>,
      "checks": [{"name": ..., "passed": bool, "summary": ..., "detail": ...}, ...],
      "diffs": [{"name": ..., "summary": ..., "added": [...], "removed": [...]}, ...]   # optional
    }

Produces a markdown comment with three sections: a 7-check status table,
a diff table (only present when validate.py was run with
--reference-snapshot), and a hidden HTML marker so the CI workflow can
find-and-update the comment on subsequent runs of the same PR.
"""
import argparse
import json
import sys
from typing import Iterable

# HTML comment marker. The CI workflow uses this to find a previous
# Batfish-diff comment and update it in place rather than spamming a
# new comment on every PR re-run. Renamed marker = orphaned comments
# on existing open PRs, so treat this string as part of the public
# contract.
COMMENT_MARKER = "<!-- batfish-diff-bot -->"


def _check_row(check: dict) -> str:
    name = check["name"]
    status = "PASS" if check["passed"] else "FAIL"
    summary = (check.get("summary") or "").replace("|", "\\|")
    return f"| `{name}` | {status} | {summary} |"


def _diff_row(diff: dict) -> str:
    """Format one diff entry as a markdown table row.

    `added` and `removed` may be lists of strings or lists of dicts
    (Batfish question results vary). For a row we just show counts;
    the per-entry details go in a collapsible block below the table.
    """
    name = diff["name"]
    added = diff.get("added") or []
    removed = diff.get("removed") or []
    summary = (diff.get("summary") or "").replace("|", "\\|")
    return f"| `{name}` | {len(added)} | {len(removed)} | {summary} |"


def _diff_details(diffs: Iterable[dict]) -> str:
    """Per-diff collapsible blocks listing the actual added/removed
    entries. Skipped for diffs with neither added nor removed."""
    lines = []
    for diff in diffs:
        added = diff.get("added") or []
        removed = diff.get("removed") or []
        if not added and not removed:
            continue
        lines.append(f"<details><summary><code>{diff['name']}</code> entries</summary>\n")
        lines.append("")
        if added:
            lines.append("**Added:**")
            lines.append("```")
            for entry in added:
                lines.append(str(entry))
            lines.append("```")
        if removed:
            lines.append("**Removed:**")
            lines.append("```")
            for entry in removed:
                lines.append(str(entry))
            lines.append("```")
        lines.append("</details>")
        lines.append("")
    return "\n".join(lines)


def render(payload: dict) -> str:
    """Build the full markdown comment from a validate.py JSON payload."""
    out = [COMMENT_MARKER, "", "## Batfish offline analysis"]

    # ----- standalone checks -----
    out.append("")
    out.append("### Standalone checks (this PR's snapshot)")
    out.append("")
    summary_line = (
        f"**Result: {payload['result']}** "
        f"({payload['passed']}/{payload['total']} passed)"
    )
    out.append(summary_line)
    out.append("")
    out.append("| Check | Status | Summary |")
    out.append("|---|---|---|")
    for check in payload.get("checks", []):
        out.append(_check_row(check))

    # ----- differential -----
    diffs = payload.get("diffs")
    out.append("")
    out.append("### Differential vs `main` baseline")
    out.append("")
    if diffs is None:
        out.append("_No reference snapshot was provided; skipped._")
    elif not diffs:
        out.append("_No differential analysis performed._")
    elif all(not (d.get("added") or d.get("removed")) for d in diffs):
        out.append(
            "**No semantic changes vs `main`.** "
            "PR's rendered configs produce the same Batfish-modelled "
            "BGP topology, IP ownership, and route set as the current "
            "`main` baseline."
        )
    else:
        out.append("| Question | Added | Removed | Summary |")
        out.append("|---|---|---|---|")
        for diff in diffs:
            out.append(_diff_row(diff))
        details = _diff_details(diffs)
        if details:
            out.append("")
            out.append(details)

    out.append("")
    out.append(
        "_Generated by phase6-cicd/scripts/format_batfish_comment.py "
        "from `validate.py --format json`._"
    )
    return "\n".join(out) + "\n"


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument(
        "--input",
        default="-",
        help="Path to validate.py JSON output, or - for stdin (default: -).",
    )
    p.add_argument(
        "--output",
        default="-",
        help="Path to write the markdown comment, or - for stdout (default: -).",
    )
    args = p.parse_args(argv)

    if args.input == "-":
        payload = json.load(sys.stdin)
    else:
        with open(args.input, encoding="utf-8") as f:
            payload = json.load(f)

    md = render(payload)

    if args.output == "-":
        sys.stdout.write(md)
    else:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(md)


if __name__ == "__main__":
    main()
