"""Regenerate raw_init_issues_*.txt fixtures from a live Batfish run.

Dumps raw initIssues() / undefinedReferences() / fileParseStatus()
against the current Phase 3 render. Bypasses questions.py entirely
so the output is what Batfish emits before the
IGNORED_INIT_ISSUE_PATTERNS and IGNORED_REF_STRUCT_TYPES filters
strip it. Those filter substrings are copied from a fixture
generated by this script, so if Batfish changes its output shape
in a future release, re-running this script and diffing the
result against the committed fixture surfaces the drift.

When to re-run:
  - The Batfish container image bumps in docker-compose.yml
  - Batfish gains Junos mac-vrf support (track batfish#5036)
  - The Phase 3 render shape changes in a way that affects what gets parsed

Invocation (from the workstation, WSL2 venv with pybatfish installed):

    wsl -d Debian -- bash -c 'export BATFISH_HOST=netdevops-srv.lab.local && \
      ~/.venvs/evpn-lab/bin/python \
        /mnt/c/Users/tasior/Projects/evpn-lab/phase4-batfish/tests/fixtures/capture_raw_output.py \
        > /mnt/c/Users/tasior/Projects/evpn-lab/phase4-batfish/tests/fixtures/raw_init_issues_YYYY-MM-DD.txt'

Point BATFISH_HOST at a live container, rename the output file with the
capture date, and commit the new fixture alongside whatever change
prompted the re-capture.
"""
import datetime as dt
import os
import shutil
import sys
import tempfile
from pathlib import Path

import pandas as pd
import pybatfish
from pybatfish.client.session import Session

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 20)
pd.set_option("display.width", 200)
pd.set_option("display.max_colwidth", 200)

BATFISH_HOST = os.environ.get("BATFISH_HOST")
if not BATFISH_HOST:
    print("BATFISH_HOST env var not set", file=sys.stderr)
    sys.exit(2)

REPO_ROOT = Path(__file__).resolve().parents[3]
BUILD_DIR = REPO_ROOT / "phase3-nornir" / "build"
if not BUILD_DIR.is_dir():
    print(f"Phase 3 build/ not found at {BUILD_DIR} - run deploy.py --full first", file=sys.stderr)
    sys.exit(2)

tmp = Path(tempfile.mkdtemp(prefix="bf-raw-"))
cfg_dir = tmp / "configs"
cfg_dir.mkdir()
for f in sorted(BUILD_DIR.glob("*.conf")):
    if f.name.endswith(".pre-commit.conf"):
        continue
    shutil.copy(f, cfg_dir / (f.stem + ".cfg"))

bf = Session(host=BATFISH_HOST)
bf.set_network("evpn-lab-raw-probe")
bf.init_snapshot(str(tmp), name="raw", overwrite=True)

print(f"# Raw Batfish output against Phase 3 build/ - captured {dt.date.today().isoformat()}")
print(f"# pybatfish version: {pybatfish.__version__}")
print(f"# Batfish host: {BATFISH_HOST}")
print(f"# Snapshot configs: {sorted(f.name for f in cfg_dir.iterdir())}")
print(f"# Generated by phase4-batfish/tests/fixtures/capture_raw_output.py")
print(f"# This fixture is the provenance backing IGNORED_INIT_ISSUE_PATTERNS")
print(f"# and IGNORED_REF_STRUCT_TYPES in phase4-batfish/questions.py, and the")
print(f"# fixture strings used by tests/test_questions.py::test_init_issues_*.")
print()

print("=" * 80)
print(" fileParseStatus()")
print("=" * 80)
ps = bf.q.fileParseStatus().answer().frame()
print(ps.to_string(index=False))
print()

print("=" * 80)
print(" initIssues() - RAW, unfiltered")
print("=" * 80)
ii = bf.q.initIssues().answer().frame()
print(f"Total rows: {len(ii)}")
if not ii.empty:
    print(f"Columns: {list(ii.columns)}")
    print()
    print(ii.to_string(index=False))
print()

print("=" * 80)
print(" undefinedReferences() - RAW, unfiltered")
print("=" * 80)
ur = bf.q.undefinedReferences().answer().frame()
print(f"Total rows: {len(ur)}")
if not ur.empty:
    print(f"Columns: {list(ur.columns)}")
    print()
    print(ur.to_string(index=False))
    print()
    print("Struct_Type breakdown:")
    print(ur["Struct_Type"].value_counts().to_string())
